# Using Google Geocoder

In [ ]:
from google_maps_geocoder.geocoder import GoogleGeocoder
import pandas as pd
import os

# Initialize the GoogleGeocoder
api_key = os.getenv("GOOGLE_API_KEY")
geocoder = GoogleGeocoder(api_key)

# Load the dataset
input_data = pd.read_csv(r"C:\Users\Miles.Vandenburg\OneDrive - Cushman & Wakefield\Client_Work\McKesson\2026\0226-ChevyChaseFriendship\Resource_Files\Patient Zip Codes for Chevy Chase and Friendship ASC from Athena_Clean_02.04.2026.csv")

# Clean and prepare the data
destinations, needs_geocoding = geocoder.cleanup_pd(input_data)

# Perform geocoding
if needs_geocoding:
    final_dest_df = geocoder.geocode_addresses(destinations, needs_geocoding)
    final_dest_df.to_csv('geocoded_results.csv', index=False)
else:
    print("Data already contains coordinates.")

# tef = geocoder.geocode_single('1099 Stewart Street,Seattle,WA')
# # df = pd.json_normalize(tef)
# tef

# Using Signed Signature

In [1]:
# Import necessary function
from google_maps_geocoder.geocode_signed_url import signed_url_geocode
import os
from concurrent.futures import ThreadPoolExecutor

private_key = os.getenv("GOOGLE_MAPS_PRIVATE_KEY")
if not private_key:
    raise ValueError("GOOGLE_MAPS_PRIVATE_KEY is not set in the environment.")
# Define parameters
input_file = r"C:\Users\Miles.Vandenburg\Documents\C&W\Client_Work\McKesson\2026\0326-CrimeMaps-Lawrenceville\Resources\NJR Lawrenceville and DVRA Lawrenceville Zip Codes_Test.csv"
output_file = 'geocoded_results_signed_url.csv'
base_url = "http://maps.googleapis.com/maps/api/geocode/json"
client = "gme-cushmanwakefield"
channel = "GBC"
# Run the script
signed_url_geocode(input_file, output_file, private_key, base_url, client, channel, geocode_only = False,limit=None)

C:\Users\Miles.Vandenburg\Documents\C&W\Client_Work\McKesson\2026\0326-CrimeMaps-Lawrenceville\Resources
<bound method NDFrame.describe of     Zip Codes  DVRA - Lawrenceville - OFF  NJR - Lawrenceville - OFF
0        8540                         271                       1602
1        8648                         364                       1261
2        8690                         299                        839
3        8619                         252                        864
4        8610                         286                        785
5        8618                         264                        766
6        8831                          40                        861
7        8550                         148                        732
8        8638                         192                        678
9        8534                         190                        598
10       8691                         169                        565
11       8520                          97                        483
12       8628                         164                        377
13       8620                         136                        397
14       8505                         156                        323
15      19067                         148                        283
16       8536                          72                        342
17       8558                          63                        310
18       8611                          67                        284
19       8501                          86                        214
20       8512                          38                        260>
Original columns: Index(['Zip Codes', 'DVRA - Lawrenceville - OFF', 'NJR - Lawrenceville - OFF'], dtype='object')
CODE UPDATED
TEST
Post-cleanup columns: Index(['Zip Codes', 'DVRA - Lawrenceville - OFF', 'NJR - Lawrenceville - OFF',
       'ADDRESS_FULL'],
      dtype='object')
Loaded 21 records from C:\Users\Miles.Vandenburg\Documents\C&W\Client_Work\McKesson\2026\0326-CrimeMaps-Lawrenceville\Resources\NJR Lawrenceville and DVRA Lawrenceville Zip Codes_Test.csv
Signed URLs have been saved to signed_urls.csv
Processing 21 URLs with parallel processing...
Processed 21/21 URLs
Successfully joined 21 records
Combined data saved to C:\Users\Miles.Vandenburg\Documents\C&W\Client_Work\McKesson\2026\0326-CrimeMaps-Lawrenceville\Resources\results\geocoded_results_signed_url.csv
Google geocoding results have been saved to geocoded_results_signed_url.csv

,formatted_address,latitude,longitude,accuracy,google_place_id,type,postcode,number_of_results,status,Site_Number,Zip Codes,DVRA - Lawrenceville - OFF,NJR - Lawrenceville - OFF,ADDRESS_FULL
0,"Princeton, NJ 08540, USA",40.381530,-74.651754,APPROXIMATE,ChIJW1m88a7kw4kRWUE08INzLEA,postal_code,08540,1,OK,1,08540,271,1602,08540
1,"Trenton, NJ 08648, USA",40.291297,-74.722002,APPROXIMATE,ChIJIatQUELiw4kR1TXM5U34gAw,postal_code,08648,1,OK,2,08648,364,1261,08648
2,"Hamilton Township, NJ 08690, USA",40.227683,-74.657609,APPROXIMATE,ChIJb_t_WRFfwYkRqixwo6Ok99c,postal_code,08690,1,OK,3,08690,299,839,08690
3,"Hamilton Township, NJ 08619, USA",40.248203,-74.698589,APPROXIMATE,ChIJhSMTGbdYwYkR2ynUfLyPbB0,postal_code,08619,1,OK,4,08619,252,864,08619
4,"Hamilton Township, NJ 08610, USA",40.195613,-74.716149,APPROXIMATE,ChIJ7SJOJWFZwYkRndzlVZifYFY,postal_code,08610,1,OK,5,08610,286,785,08610
5,"Trenton, NJ 08618, USA",40.245027,-74.786370,APPROXIMATE,ChIJTRXRC4xXwYkRARdlC0NWykE,postal_code,08618,1,OK,6,08618,264,766,08618
6,"Monroe Township, NJ 08831, USA",40.336287,-74.432985,APPROXIMATE,ChIJPZtNBmnaw4kR0lCbSXa_wEU,postal_code,08831,1,OK,7,08831,40,861,08831
7,"West Windsor Township, NJ 08550, USA",40.278636,-74.628332,APPROXIMATE,ChIJg3qj_lvgw4kRWTcAZ4VslvQ,postal_code,08550,1,OK,8,08550,148,732,08550
8,"Trenton, NJ 08638, USA",40.251875,-74.762966,APPROXIMATE,ChIJ6ycNoA1YwYkRCmhetZcoqD8,postal_code,08638,1,OK,9,08638,192,678,08638
9,"Pennington, NJ 08534, USA",40.320695,-74.792220,APPROXIMATE,ChIJy6MXdWb8w4kRBgVH_smvXmo,postal_code,08534,1,OK,10,08534,190,598,08534
10,"Hamilton Township, NJ 08691, USA",40.215546,-74.604906,APPROXIMATE,ChIJw_2uTRdewYkRKifMChzdhUw,postal_code,08691,1,OK,11,08691,169,565,08691
11,"East Windsor, NJ 08520, USA",40.265887,-74.534610,APPROXIMATE,ChIJ4SxYkz_fw4kRi-4gFE342LI,postal_code,08520,1,OK,12,08520,97,483,08520
12,"Trenton, NJ 08628, USA",40.269707,-74.821469,APPROXIMATE,ChIJYfwW1DxYwYkR0aqS06A6Os0,postal_code,08628,1,OK,13,08628,164,377,08628
13,"Hamilton Township, NJ 08620, USA",40.177714,-74.657609,APPROXIMATE,ChIJhR_jrghcwYkRfljb3Vo0zec,postal_code,08620,1,OK,14,08620,136,397,08620
14,"Bordentown, NJ 08505, USA",40.118735,-74.739559,APPROXIMATE,ChIJ91hq0NFEwYkR3G8WC6iu6D8,postal_code,08505,1,OK,15,08505,156,323,08505
15,"Morrisville, PA 19067, USA",40.218657,-74.850713,APPROXIMATE,ChIJq4bSmkBWwYkRxtr0GefYxQY,postal_code,19067,1,OK,16,19067,148,283,19067
16,"Plainsboro Township, NJ 08536, USA",40.337904,-74.587335,APPROXIMATE,ChIJq9BjCfTdw4kRsQieARE88_Q,postal_code,08536,1,OK,17,08536,72,342,08536
17,"Skillman, NJ 08558, USA",40.410949,-74.722002,APPROXIMATE,ChIJbeCcYPblw4kRuQtIppiyjRU,postal_code,08558,1,OK,18,08558,63,310,08558
18,"Hamilton Township, NJ 08611, USA",40.203230,-74.754189,APPROXIMATE,ChIJx6DecSpawYkRZJ9nOrrZR6Y,postal_code,08611,1,OK,19,08611,67,284,08611
19,"Allentown, NJ 08501, USA",40.169202,-74.558045,APPROXIMATE,ChIJucsTZiBnwYkR5CGxPJfWb-I,postal_code,08501,1,OK,20,08501,86,214,08501
20,"East Windsor, NJ 08512, USA",40.322533,-74.511172,APPROXIMATE,ChIJ9ZUoHSTcw4kRyGXYXlI_zew,postal_code,08512,1,OK,21,08512,38,260,08512

## Using Signed SIgnature for Reverse Geocoding

In [1]:
"""
Example: Reverse Geocoding (Lat/Lon to Address)
Converts geographic coordinates to addresses
"""

# Import necessary function
from google_maps_geocoder.geocode_signed_url_enhanced import signed_url_geocode
import os

# Get API credentials from environment
private_key = os.getenv("GOOGLE_MAPS_PRIVATE_KEY")
if not private_key:
    raise ValueError("GOOGLE_MAPS_PRIVATE_KEY is not set in the environment.")

# Define parameters for REVERSE geocoding
input_file = r"C:\Users\Miles.Vandenburg\Documents\C&W\Client_Work\Sonepar\1025-DatacenterPulls-Worldwide\Resource_Files\Test_Reverse_Geocode.csv"  # Your CSV file with latitude and longitude columns
output_file = r'geocoded_results_reverse.csv'
base_url = "http://maps.googleapis.com/maps/api/geocode/json"
client = "gme-cushmanwakefield"
channel = "GBC"

# Run REVERSE geocoding (lat/lon -> address)
print("Starting Reverse Geocoding...")
results = signed_url_geocode(
    input_file=input_file,
    output_file=output_file,
    private_key=private_key,
    base_url=base_url,
    client=client,
    channel=channel,
    geocode_only=False,      # Generate new signed URLs
    limit=None,              # Process all rows (or set to a number like 100 for testing)
    reverse_geocode=True,    # REVERSE geocoding mode (lat/lon -> address)
    lat_col='latitude',      # Name of your latitude column
    lon_col='longitude'      # Name of your longitude column
)

print(f"\nReverse geocoding complete! Results shape: {results.shape}")
print(f"\nOutput columns: {results.columns.tolist()}")

# Display sample results
print("\nSample results (first 5 rows):")
# print(results[['formatted_address', 'city', 'state', 'country', 'postcode']].head())

Starting Reverse Geocoding...
Working directory: C:\Users\Miles.Vandenburg\Documents\C&W\Client_Work\Sonepar\1025-DatacenterPulls-Worldwide\Resource_Files
============================================================
REVERSE GEOCODING MODE: Converting lat/lon to addresses
============================================================
Original columns: ['id', 'name', 'company_name', 'country', 'longitude', 'latitude', 'm2_space', 'gross_max_power_kw', 'ready_for_service_date', 'construction_date', 'cert_uptime_tier_level', 'cert_uptime_tier', 'cert_leed', 'cert_breeam', 'cert_eu_coc', 'cert_other', 'cdns', 'networks', 'fibres', 'ixps', 'clouds']
Loaded 2067 records from C:\Users\Miles.Vandenburg\Documents\C&W\Client_Work\Sonepar\1025-DatacenterPulls-Worldwide\Resource_Files\Test_Reverse_Geocode.csv
Loaded 2067 records from C:\Users\Miles.Vandenburg\Documents\C&W\Client_Work\Sonepar\1025-DatacenterPulls-Worldwide\Resource_Files\Test_Reverse_Geocode.csv
Saved cleaned data to C:\Users\Miles.Vandenburg\Documents\C&W\Client_Work\Sonepar\1025-DatacenterPulls-Worldwide\Resource_Files\results\site_numbered_cleaned_data.csv
Signed URLs have been saved to signed_urls.csv
Processing 2067 URLs with parallel processing...
Processed 100/2067 URLs
Processed 200/2067 URLs
Processed 300/2067 URLs
Processed 400/2067 URLs
Processed 500/2067 URLs
Processed 600/2067 URLs
Processed 700/2067 URLs
Processed 800/2067 URLs
Processed 900/2067 URLs
Processed 1000/2067 URLs
Processed 1100/2067 URLs
Processed 1200/2067 URLs
Processed 1300/2067 URLs
Processed 1400/2067 URLs
Processed 1500/2067 URLs
Processed 1600/2067 URLs
Processed 1700/2067 URLs
Processed 1800/2067 URLs
Processed 1900/2067 URLs
Processed 2000/2067 URLs
Processed 2067/2067 URLs
Saved Google results to C:\Users\Miles.Vandenburg\Documents\C&W\Client_Work\Sonepar\1025-DatacenterPulls-Worldwide\Resource_Files\results\google_results_df.csv
Successfully joined 2067 records
Combined data saved to C:\Users\Miles.Vandenburg\Documents\C&W\Client_Work\Sonepar\1025-DatacenterPulls-Worldwide\Resource_Files\results\geocoded_results_reverse.csv
============================================================
COMPLETE: Results saved to geocoded_results_reverse.csv
============================================================

Reverse geocoding complete! Results shape: (2067, 39)

Output columns: ['formatted_address', 'street_number', 'street_name', 'city', 'county', 'state', 'state_code', 'country_x', 'country_code', 'postcode', 'latitude_x', 'longitude_x', 'accuracy', 'google_place_id', 'type', 'number_of_results', 'status', 'Site_Number', 'id', 'name', 'company_name', 'country_y', 'longitude_y', 'latitude_y', 'm2_space', 'gross_max_power_kw', 'ready_for_service_date', 'construction_date', 'cert_uptime_tier_level', 'cert_uptime_tier', 'cert_leed', 'cert_breeam', 'cert_eu_coc', 'cert_other', 'cdns', 'networks', 'fibres', 'ixps', 'clouds']

Sample results (first 5 rows):

In [ ]:
results.to_ss

,formatted_address,street_number,street_name,city,county,state,state_code,country_x,country_code,postcode,...,cert_uptime_tier,cert_leed,cert_breeam,cert_eu_coc,cert_other,cdns,networks,fibres,ixps,clouds
0,"2045 Chenault Dr, Carrollton, TX 75006, USA",2045,Chenault Drive,Carrollton,Dallas County,Texas,TX,United States,US,75006,...,0.0,False,False,False,NaN,NaN,NaN,NaN,NaN,NaN
1,"629 Fairview Ave N, St Paul, MN 55104, USA",629,Fairview Avenue North,Saint Paul,Ramsey County,Minnesota,MN,United States,US,55104,...,0.0,False,False,False,NaN,NaN,NaN,NaN,NaN,NaN
2,"155-179 Myers Corners Rd, Wappingers Falls, NY...",155-179,Myers Corners Road,Wappingers Falls,Dutchess County,New York,NY,United States,US,12590,...,0.0,False,False,False,NaN,NaN,NaN,NaN,NaN,NaN
3,"25 Madison Rd, Totowa, NJ 07512, USA",25,Madison Road,Totowa,Passaic County,New Jersey,NJ,United States,US,07512,...,0.0,False,False,False,NaN,NaN,NaN,NaN,NaN,NaN
4,"18 Roxbury Rd, Norwalk, CT 06855, USA",18,Roxbury Road,Norwalk,Western Connecticut Planning Region,Connecticut,CT,United States,US,06855,...,0.0,False,False,False,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2062,"300 Franklin Ave, Waco, TX 76701, USA",300,Franklin Avenue,Waco,McLennan County,Texas,TX,United States,US,76701,...,0.0,False,False,False,NaN,NaN,NaN,NaN,NaN,NaN
2063,"697 Woodlane St, Little Rock, AR 72201, USA",697,Woodlane Street,Little Rock,Pulaski County,Arkansas,AR,United States,US,72201,...,0.0,False,False,False,NaN,NaN,NaN,NaN,NaN,NaN
2064,"18070 Jefferson Davis Hwy, Ruther Glen, VA 225...",18070,Jefferson Davis Highway,Ruther Glen,Caroline County,Virginia,VA,United States,US,22546,...,0.0,False,False,False,NaN,NaN,NaN,NaN,NaN,NaN
2065,"9663 87th Ave SE, Ellendale, ND 58436, USA",9663,87th Avenue Southeast,Ellendale,Dickey County,North Dakota,ND,United States,US,58436,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2066,"9120 Nieman Rd, Overland Park, KS 66214, USA",9120,Nieman Road,Overland Park,Johnson County,Kansas,KS,United States,US,66214,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# Address Validation

## Multiple Columns

In [ ]:
from google_maps_geocoder import AddressValidator

validator = AddressValidator()

# This will now work - it auto-detects columns!
results = validator.validate_csv_addresses(
    r"C:\Users\Miles.Vandenburg\Downloads\Test 2.csv"
)
# See what columns are available and get suggestions
validator.print_column_inspection(
    r"C:\Users\Miles.Vandenburg\Downloads\Test 2.csv"
)

# # Specify columns manually if auto-detection doesn't work
# results = validator.validate_csv_addresses(
#     csv_file_path=r'C:\Users\Miles.Vandenburg\Documents\Python_Projects\Google_Maps_Geocoder\Examples\inputs\example_address.csv',
#     address_col="Street_Address",  # Your actual column name
#     city_col="City_Name",          # Your actual column name
#     state_col="State_Code",        # Your actual column name
#     zip_col="Postal_Code",         # Your actual column name
#     output_file='validated_addresses.csv'
# )

## Single Column

In [ ]:
from google_maps_geocoder import Config, AddressValidator

# # Force API key method
# config = Config(google_api_key="your-api-key")
# validator = AddressValidator(config)
# private_key = os.getenv("GOOGLE_MAPS_PRIVATE_KEY")
# config = Config(
#     google_client_id="gme-cushmanwakefield",
#     google_private_key=private_key,
#     channel="GBC",
#     # Don't set google_api_key - forces signed URL usage
# )
# validator = AddressValidator(config)
config = Config(google_api_key=os.getenv("GOOGLE_API_KEY"))
validator = AddressValidator(config)

# Your Test_set.csv validation
results = validator.validate_csv_addresses(
    r"C:\Users\Miles.Vandenburg\Documents\Python_Projects\Google_Maps_Geocoder_clean\Examples\inputs\example_address.csv"
)

### Full Test Single Column

In [ ]:
from google_maps_geocoder import AddressValidator

private_key = os.getenv("GOOGLE_API_KEY")
config = Config(google_api_key=private_key)
validator = AddressValidator(config)

# Auto-detect mode will find FULL_Address column
# results = validator.validate_csv_addresses(r"C:\Users\Miles.Vandenburg\Downloads\Test 2.csv")
results_Test_1 = validator.validate_csv_addresses(r"C:\Users\Miles.Vandenburg\Downloads\Test 1.csv")


# See detailed analysis of your CSV
validator.print_column_inspection(r"C:\Users\Miles.Vandenburg\Downloads\Test 2.csv")
validator.print_column_inspection(r"C:\Users\Miles.Vandenburg\Downloads\Test 1.csv")

# Access specific results
valid_addresses = results[results['is_valid'] == True]
invalid_addresses = results[results['is_valid'] == False]

valid_addresses_results_Test_1 = results_Test_1[results_Test_1['is_valid'] == True]
invalid_addresses_results_Test_1 = results_Test_1[results_Test_1['is_valid'] == False]

# Get formatted addresses
formatted = results['formatted_address'].dropna().tolist()
formatted_results_Test_1 = results_Test_1['formatted_address'].dropna().tolist()

# Check validation rate
validation_rate = (results['is_valid'].sum() / len(results)) * 100
print(f"Validation rate: {validation_rate:.1f}%")

validation_rate_results_Test_1 = (results_Test_1['is_valid'].sum() / len(results_Test_1)) * 100
print(f"Validation rate: {validation_rate_results_Test_1:.1f}%")

2025-07-15 15:24:48,157 - google_maps_geocoder - INFO - Using API key authentication
2025-07-15 15:24:48,181 - google_maps_geocoder - INFO - Loading CSV file: C:\Users\Miles.Vandenburg\Downloads\Test 2.csv
2025-07-15 15:24:48,194 - google_maps_geocoder - INFO - Loaded 8716 rows
2025-07-15 15:24:48,196 - google_maps_geocoder - INFO - Using default region: US
2025-07-15 15:24:48,198 - google_maps_geocoder - INFO - Using existing full address column: FULL_Address
2025-07-15 15:24:48,199 - google_maps_geocoder - INFO - Processing batch 1: rows 1 to 100

🔍 No column names specified. Attempting auto-detection...
✅ Detected single address format:
   Full Address: FULL_Address
✅ Using single address column: 'FULL_Address'

2025-07-15 15:25:11,998 - google_maps_geocoder - INFO - Progress: 50/8716 addresses processed
2025-07-15 15:25:35,848 - google_maps_geocoder - INFO - Progress: 100/8716 addresses processed
2025-07-15 15:25:35,849 - google_maps_geocoder - INFO - Processing batch 2: rows 101 to 200
2025-07-15 15:25:58,864 - google_maps_geocoder - INFO - Progress: 150/8716 addresses processed
2025-07-15 15:26:22,283 - google_maps_geocoder - INFO - Progress: 200/8716 addresses processed
2025-07-15 15:26:22,284 - google_maps_geocoder - INFO - Processing batch 3: rows 201 to 300
2025-07-15 15:26:45,782 - google_maps_geocoder - INFO - Progress: 250/8716 addresses processed
2025-07-15 15:27:09,142 - google_maps_geocoder - INFO - Progress: 300/8716 addresses processed
2025-07-15 15:27:09,143 - google_maps_geocoder - INFO - Processing batch 4: rows 301 to 400
2025-07-15 15:27:32,640 - google_maps_geocoder - INFO - Progress: 350/8716 addresses processed
2025-07-15 15:27:55,499 - google_maps_geocoder - INFO - Progress: 400/8716 addresses processed
2025-07-15 15:27:55,500 - google_maps_geocoder - INFO - Processing batch 5: rows 401 to 500
2025-07-15 15:28:17,761 - google_maps_geocoder - INFO - Progress: 450/8716 addresses processed
2025-07-15 15:28:41,410 - google_maps_geocoder - INFO - Progress: 500/8716 addresses processed
2025-07-15 15:28:41,411 - google_maps_geocoder - INFO - Processing batch 6: rows 501 to 600
2025-07-15 15:29:05,738 - google_maps_geocoder - INFO - Progress: 550/8716 addresses processed
2025-07-15 15:29:29,218 - google_maps_geocoder - INFO - Progress: 600/8716 addresses processed
2025-07-15 15:29:29,220 - google_maps_geocoder - INFO - Processing batch 7: rows 601 to 700
2025-07-15 15:29:53,054 - google_maps_geocoder - INFO - Progress: 650/8716 addresses processed
2025-07-15 15:30:15,927 - google_maps_geocoder - INFO - Progress: 700/8716 addresses processed
2025-07-15 15:30:15,928 - google_maps_geocoder - INFO - Processing batch 8: rows 701 to 800
2025-07-15 15:30:38,733 - google_maps_geocoder - INFO - Progress: 750/8716 addresses processed
2025-07-15 15:31:00,727 - google_maps_geocoder - INFO - Progress: 800/8716 addresses processed
2025-07-15 15:31:00,729 - google_maps_geocoder - INFO - Processing batch 9: rows 801 to 900
2025-07-15 15:31:23,865 - google_maps_geocoder - INFO - Progress: 850/8716 addresses processed
2025-07-15 15:31:45,169 - google_maps_geocoder - INFO - Progress: 900/8716 addresses processed
2025-07-15 15:31:45,171 - google_maps_geocoder - INFO - Processing batch 10: rows 901 to 1000
2025-07-15 15:32:07,312 - google_maps_geocoder - INFO - Progress: 950/8716 addresses processed
2025-07-15 15:32:29,016 - google_maps_geocoder - INFO - Progress: 1000/8716 addresses processed
2025-07-15 15:32:29,017 - google_maps_geocoder - INFO - Processing batch 11: rows 1001 to 1100
2025-07-15 15:32:51,156 - google_maps_geocoder - INFO - Progress: 1050/8716 addresses processed
2025-07-15 15:33:13,539 - google_maps_geocoder - INFO - Progress: 1100/8716 addresses processed
2025-07-15 15:33:13,540 - google_maps_geocoder - INFO - Processing batch 12: rows 1101 to 1200
2025-07-15 15:33:35,408 - google_maps_geocoder - INFO - Progress: 1150/8716 addresses processed
2025-07-15 15:33:58,724 - google_maps_geocoder - INFO - Progress: 1200/8716 addresses processed
2025-07-15 15:33:58,726 - google_maps_geocoder - INFO - Processing batch 13: rows 1201 to 1300
2025-07-15 15:34:23,080 - google_maps_geocoder - INFO - Progress: 1250/8716 addresses processed
2025-07-15 15:34:46,846 - google_maps_geocoder - INFO - Progress: 1300/8716 addresses processed
2025-07-15 15:34:46,847 - google_maps_geocoder - INFO - Processing batch 14: rows 1301 to 1400
2025-07-15 15:35:10,991 - google_maps_geocoder - INFO - Progress: 1350/8716 addresses processed
2025-07-15 15:35:34,193 - google_maps_geocoder - INFO - Progress: 1400/8716 addresses processed
2025-07-15 15:35:34,194 - google_maps_geocoder - INFO - Processing batch 15: rows 1401 to 1500
2025-07-15 15:35:56,594 - google_maps_geocoder - INFO - Progress: 1450/8716 addresses processed
2025-07-15 15:36:21,338 - google_maps_geocoder - INFO - Progress: 1500/8716 addresses processed
2025-07-15 15:36:21,339 - google_maps_geocoder - INFO - Processing batch 16: rows 1501 to 1600
2025-07-15 15:36:43,765 - google_maps_geocoder - INFO - Progress: 1550/8716 addresses processed
2025-07-15 15:37:06,280 - google_maps_geocoder - INFO - Progress: 1600/8716 addresses processed
2025-07-15 15:37:06,281 - google_maps_geocoder - INFO - Processing batch 17: rows 1601 to 1700
2025-07-15 15:37:28,016 - google_maps_geocoder - INFO - Progress: 1650/8716 addresses processed
2025-07-15 15:37:49,845 - google_maps_geocoder - INFO - Progress: 1700/8716 addresses processed
2025-07-15 15:37:49,846 - google_maps_geocoder - INFO - Processing batch 18: rows 1701 to 1800
2025-07-15 15:38:11,916 - google_maps_geocoder - INFO - Progress: 1750/8716 addresses processed
2025-07-15 15:38:24,921 - google_maps_geocoder - ERROR - HTTP Error 500: {
  "error": {
    "code": 500,
    "message": "Internal error encountered.",
    "status": "INTERNAL"
  }
}

2025-07-15 15:38:34,617 - google_maps_geocoder - INFO - Progress: 1800/8716 addresses processed
2025-07-15 15:38:34,618 - google_maps_geocoder - INFO - Processing batch 19: rows 1801 to 1900
2025-07-15 15:38:56,415 - google_maps_geocoder - INFO - Progress: 1850/8716 addresses processed
2025-07-15 15:39:18,178 - google_maps_geocoder - INFO - Progress: 1900/8716 addresses processed
2025-07-15 15:39:18,179 - google_maps_geocoder - INFO - Processing batch 20: rows 1901 to 2000
2025-07-15 15:39:40,030 - google_maps_geocoder - INFO - Progress: 1950/8716 addresses processed
2025-07-15 15:40:01,925 - google_maps_geocoder - INFO - Progress: 2000/8716 addresses processed
2025-07-15 15:40:01,926 - google_maps_geocoder - INFO - Processing batch 21: rows 2001 to 2100
2025-07-15 15:40:24,255 - google_maps_geocoder - INFO - Progress: 2050/8716 addresses processed
2025-07-15 15:40:45,394 - google_maps_geocoder - INFO - Progress: 2100/8716 addresses processed
2025-07-15 15:40:45,396 - google_maps_geocoder - INFO - Processing batch 22: rows 2101 to 2200
2025-07-15 15:41:06,474 - google_maps_geocoder - INFO - Progress: 2150/8716 addresses processed
2025-07-15 15:41:27,352 - google_maps_geocoder - INFO - Progress: 2200/8716 addresses processed
2025-07-15 15:41:27,354 - google_maps_geocoder - INFO - Processing batch 23: rows 2201 to 2300
2025-07-15 15:41:47,921 - google_maps_geocoder - INFO - Progress: 2250/8716 addresses processed
2025-07-15 15:42:08,187 - google_maps_geocoder - INFO - Progress: 2300/8716 addresses processed
2025-07-15 15:42:08,188 - google_maps_geocoder - INFO - Processing batch 24: rows 2301 to 2400
2025-07-15 15:42:29,103 - google_maps_geocoder - INFO - Progress: 2350/8716 addresses processed
2025-07-15 15:42:49,728 - google_maps_geocoder - INFO - Progress: 2400/8716 addresses processed
2025-07-15 15:42:49,729 - google_maps_geocoder - INFO - Processing batch 25: rows 2401 to 2500
2025-07-15 15:43:10,200 - google_maps_geocoder - INFO - Progress: 2450/8716 addresses processed
2025-07-15 15:43:31,582 - google_maps_geocoder - INFO - Progress: 2500/8716 addresses processed
2025-07-15 15:43:31,583 - google_maps_geocoder - INFO - Processing batch 26: rows 2501 to 2600
2025-07-15 15:43:53,758 - google_maps_geocoder - INFO - Progress: 2550/8716 addresses processed
2025-07-15 15:44:16,312 - google_maps_geocoder - INFO - Progress: 2600/8716 addresses processed
2025-07-15 15:44:16,313 - google_maps_geocoder - INFO - Processing batch 27: rows 2601 to 2700
2025-07-15 15:44:39,205 - google_maps_geocoder - INFO - Progress: 2650/8716 addresses processed
2025-07-15 15:45:01,513 - google_maps_geocoder - INFO - Progress: 2700/8716 addresses processed
2025-07-15 15:45:01,514 - google_maps_geocoder - INFO - Processing batch 28: rows 2701 to 2800
2025-07-15 15:45:24,379 - google_maps_geocoder - INFO - Progress: 2750/8716 addresses processed
2025-07-15 15:45:47,331 - google_maps_geocoder - INFO - Progress: 2800/8716 addresses processed
2025-07-15 15:45:47,333 - google_maps_geocoder - INFO - Processing batch 29: rows 2801 to 2900
2025-07-15 15:46:11,430 - google_maps_geocoder - INFO - Progress: 2850/8716 addresses processed
2025-07-15 15:46:34,623 - google_maps_geocoder - INFO - Progress: 2900/8716 addresses processed
2025-07-15 15:46:34,624 - google_maps_geocoder - INFO - Processing batch 30: rows 2901 to 3000
2025-07-15 15:46:56,898 - google_maps_geocoder - INFO - Progress: 2950/8716 addresses processed
2025-07-15 15:47:19,711 - google_maps_geocoder - INFO - Progress: 3000/8716 addresses processed
2025-07-15 15:47:19,712 - google_maps_geocoder - INFO - Processing batch 31: rows 3001 to 3100
2025-07-15 15:47:43,137 - google_maps_geocoder - INFO - Progress: 3050/8716 addresses processed
2025-07-15 15:47:57,844 - google_maps_geocoder - ERROR - HTTP Error 500: {
  "error": {
    "code": 500,
    "message": "Internal error encountered.",
    "status": "INTERNAL"
  }
}

2025-07-15 15:48:06,174 - google_maps_geocoder - INFO - Progress: 3100/8716 addresses processed
2025-07-15 15:48:06,175 - google_maps_geocoder - INFO - Processing batch 32: rows 3101 to 3200
2025-07-15 15:48:28,978 - google_maps_geocoder - INFO - Progress: 3150/8716 addresses processed
2025-07-15 15:48:52,521 - google_maps_geocoder - INFO - Progress: 3200/8716 addresses processed
2025-07-15 15:48:52,523 - google_maps_geocoder - INFO - Processing batch 33: rows 3201 to 3300
2025-07-15 15:49:15,094 - google_maps_geocoder - INFO - Progress: 3250/8716 addresses processed
2025-07-15 15:49:36,592 - google_maps_geocoder - INFO - Progress: 3300/8716 addresses processed
2025-07-15 15:49:36,593 - google_maps_geocoder - INFO - Processing batch 34: rows 3301 to 3400
2025-07-15 15:49:58,634 - google_maps_geocoder - INFO - Progress: 3350/8716 addresses processed
2025-07-15 15:50:21,115 - google_maps_geocoder - INFO - Progress: 3400/8716 addresses processed
2025-07-15 15:50:21,116 - google_maps_geocoder - INFO - Processing batch 35: rows 3401 to 3500
2025-07-15 15:50:43,239 - google_maps_geocoder - INFO - Progress: 3450/8716 addresses processed
2025-07-15 15:51:05,953 - google_maps_geocoder - INFO - Progress: 3500/8716 addresses processed
2025-07-15 15:51:05,955 - google_maps_geocoder - INFO - Processing batch 36: rows 3501 to 3600
2025-07-15 15:51:28,708 - google_maps_geocoder - INFO - Progress: 3550/8716 addresses processed
2025-07-15 15:51:51,056 - google_maps_geocoder - INFO - Progress: 3600/8716 addresses processed
2025-07-15 15:51:51,057 - google_maps_geocoder - INFO - Processing batch 37: rows 3601 to 3700
2025-07-15 15:52:12,616 - google_maps_geocoder - INFO - Progress: 3650/8716 addresses processed
2025-07-15 15:52:34,681 - google_maps_geocoder - INFO - Progress: 3700/8716 addresses processed
2025-07-15 15:52:34,682 - google_maps_geocoder - INFO - Processing batch 38: rows 3701 to 3800
2025-07-15 15:52:57,200 - google_maps_geocoder - INFO - Progress: 3750/8716 addresses processed
2025-07-15 15:53:20,457 - google_maps_geocoder - INFO - Progress: 3800/8716 addresses processed
2025-07-15 15:53:20,457 - google_maps_geocoder - INFO - Processing batch 39: rows 3801 to 3900
2025-07-15 15:53:44,613 - google_maps_geocoder - INFO - Progress: 3850/8716 addresses processed
2025-07-15 15:54:09,633 - google_maps_geocoder - INFO - Progress: 3900/8716 addresses processed
2025-07-15 15:54:09,634 - google_maps_geocoder - INFO - Processing batch 40: rows 3901 to 4000
2025-07-15 15:54:33,832 - google_maps_geocoder - INFO - Progress: 3950/8716 addresses processed
2025-07-15 15:54:57,954 - google_maps_geocoder - INFO - Progress: 4000/8716 addresses processed
2025-07-15 15:54:57,956 - google_maps_geocoder - INFO - Processing batch 41: rows 4001 to 4100
2025-07-15 15:55:21,989 - google_maps_geocoder - INFO - Progress: 4050/8716 addresses processed
2025-07-15 15:55:46,408 - google_maps_geocoder - INFO - Progress: 4100/8716 addresses processed
2025-07-15 15:55:46,409 - google_maps_geocoder - INFO - Processing batch 42: rows 4101 to 4200
2025-07-15 15:56:09,760 - google_maps_geocoder - INFO - Progress: 4150/8716 addresses processed
2025-07-15 15:56:32,130 - google_maps_geocoder - INFO - Progress: 4200/8716 addresses processed
2025-07-15 15:56:32,131 - google_maps_geocoder - INFO - Processing batch 43: rows 4201 to 4300
2025-07-15 15:56:55,575 - google_maps_geocoder - INFO - Progress: 4250/8716 addresses processed
2025-07-15 15:57:19,676 - google_maps_geocoder - INFO - Progress: 4300/8716 addresses processed
2025-07-15 15:57:19,677 - google_maps_geocoder - INFO - Processing batch 44: rows 4301 to 4400
2025-07-15 15:57:42,972 - google_maps_geocoder - INFO - Progress: 4350/8716 addresses processed
2025-07-15 15:58:06,870 - google_maps_geocoder - INFO - Progress: 4400/8716 addresses processed
2025-07-15 15:58:06,871 - google_maps_geocoder - INFO - Processing batch 45: rows 4401 to 4500
2025-07-15 15:58:30,359 - google_maps_geocoder - INFO - Progress: 4450/8716 addresses processed
2025-07-15 15:58:54,181 - google_maps_geocoder - INFO - Progress: 4500/8716 addresses processed
2025-07-15 15:58:54,182 - google_maps_geocoder - INFO - Processing batch 46: rows 4501 to 4600
2025-07-15 15:59:17,958 - google_maps_geocoder - INFO - Progress: 4550/8716 addresses processed
2025-07-15 15:59:41,954 - google_maps_geocoder - INFO - Progress: 4600/8716 addresses processed
2025-07-15 15:59:41,955 - google_maps_geocoder - INFO - Processing batch 47: rows 4601 to 4700
2025-07-15 16:00:06,014 - google_maps_geocoder - INFO - Progress: 4650/8716 addresses processed
2025-07-15 16:00:29,352 - google_maps_geocoder - INFO - Progress: 4700/8716 addresses processed
2025-07-15 16:00:29,353 - google_maps_geocoder - INFO - Processing batch 48: rows 4701 to 4800
2025-07-15 16:00:52,647 - google_maps_geocoder - INFO - Progress: 4750/8716 addresses processed
2025-07-15 16:01:16,275 - google_maps_geocoder - INFO - Progress: 4800/8716 addresses processed
2025-07-15 16:01:16,276 - google_maps_geocoder - INFO - Processing batch 49: rows 4801 to 4900
2025-07-15 16:01:39,837 - google_maps_geocoder - INFO - Progress: 4850/8716 addresses processed
2025-07-15 16:02:02,553 - google_maps_geocoder - INFO - Progress: 4900/8716 addresses processed
2025-07-15 16:02:02,554 - google_maps_geocoder - INFO - Processing batch 50: rows 4901 to 5000
2025-07-15 16:02:25,671 - google_maps_geocoder - INFO - Progress: 4950/8716 addresses processed
2025-07-15 16:02:49,713 - google_maps_geocoder - INFO - Progress: 5000/8716 addresses processed
2025-07-15 16:02:49,714 - google_maps_geocoder - INFO - Processing batch 51: rows 5001 to 5100
2025-07-15 16:03:13,559 - google_maps_geocoder - INFO - Progress: 5050/8716 addresses processed
2025-07-15 16:03:36,347 - google_maps_geocoder - INFO - Progress: 5100/8716 addresses processed
2025-07-15 16:03:36,348 - google_maps_geocoder - INFO - Processing batch 52: rows 5101 to 5200
2025-07-15 16:04:01,928 - google_maps_geocoder - INFO - Progress: 5150/8716 addresses processed
2025-07-15 16:04:26,514 - google_maps_geocoder - INFO - Progress: 5200/8716 addresses processed
2025-07-15 16:04:26,515 - google_maps_geocoder - INFO - Processing batch 53: rows 5201 to 5300
2025-07-15 16:04:50,109 - google_maps_geocoder - INFO - Progress: 5250/8716 addresses processed
2025-07-15 16:05:16,188 - google_maps_geocoder - INFO - Progress: 5300/8716 addresses processed
2025-07-15 16:05:16,189 - google_maps_geocoder - INFO - Processing batch 54: rows 5301 to 5400
2025-07-15 16:05:40,367 - google_maps_geocoder - INFO - Progress: 5350/8716 addresses processed
2025-07-15 16:06:04,163 - google_maps_geocoder - INFO - Progress: 5400/8716 addresses processed
2025-07-15 16:06:04,164 - google_maps_geocoder - INFO - Processing batch 55: rows 5401 to 5500
2025-07-15 16:06:28,729 - google_maps_geocoder - INFO - Progress: 5450/8716 addresses processed
2025-07-15 16:06:52,508 - google_maps_geocoder - INFO - Progress: 5500/8716 addresses processed
2025-07-15 16:06:52,509 - google_maps_geocoder - INFO - Processing batch 56: rows 5501 to 5600
2025-07-15 16:07:15,573 - google_maps_geocoder - INFO - Progress: 5550/8716 addresses processed
2025-07-15 16:07:38,514 - google_maps_geocoder - INFO - Progress: 5600/8716 addresses processed
2025-07-15 16:07:38,515 - google_maps_geocoder - INFO - Processing batch 57: rows 5601 to 5700
2025-07-15 16:08:02,070 - google_maps_geocoder - INFO - Progress: 5650/8716 addresses processed
2025-07-15 16:08:24,533 - google_maps_geocoder - INFO - Progress: 5700/8716 addresses processed
2025-07-15 16:08:24,535 - google_maps_geocoder - INFO - Processing batch 58: rows 5701 to 5800
2025-07-15 16:08:49,699 - google_maps_geocoder - INFO - Progress: 5750/8716 addresses processed
2025-07-15 16:09:14,197 - google_maps_geocoder - INFO - Progress: 5800/8716 addresses processed
2025-07-15 16:09:14,198 - google_maps_geocoder - INFO - Processing batch 59: rows 5801 to 5900
2025-07-15 16:09:38,477 - google_maps_geocoder - INFO - Progress: 5850/8716 addresses processed
2025-07-15 16:10:02,906 - google_maps_geocoder - INFO - Progress: 5900/8716 addresses processed
2025-07-15 16:10:02,908 - google_maps_geocoder - INFO - Processing batch 60: rows 5901 to 6000

KeyboardInterrupt: